# NLP with Machine Learning Assignments

## 1. Sentiment Analysis

1. Create a new _nlp_machine_learning_ environment
2. Launch Jupyter Notebook
3. Read in the _movie_reviews.csv_ file
4. Apply sentiment analysis to the _movie_info_ column
5. Sort the sentiment scores to return the top 10 and bottom 10 sentiment scores and their corresponding movie titles

In [2]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
data = pd.read_csv('../NLP_basic/Data/movie_reviews.csv')
data.head(2)

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit."
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity."

In [3]:
df = data.copy()
df.head(2)

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit."
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity."

In [4]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores(data['movie_info'])['compound']

0.9999

In [5]:
def sentiment_score(text):
    analyzer = SentimentIntensityAnalyzer()
    return analyzer.polarity_scores(text)['compound']

In [6]:
df['sentiment_score'] = df['movie_info'].apply(sentiment_score)
df

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus,sentiment_score
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit.",0.9837
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity.",0.9237
2,A Tuba to Cuba,NR,"Documentary, Musical & Performing Arts",2/15/19,"The leader of New Orleans' famed Preservation Hall Jazz Band seeks to fulfill his late father's dream of retracing their musical roots to the shores of Cuba in search of the indigenous music that gave birth to New Orleans jazz. A TUBA TO CUBA celebrates the triumph of the human spirit expressed through the universal language of music and challenges us to resolve to build bridges, not walls.","Danny Clinch, T.G. Herrington",male,100,82,NaN,0.9360
3,A Vigilante,R,Drama,3/29/19,"A once abused woman, Sadie (Olivia Wilde), devotes herself to ridding victims of their domestic abusers while hunting down the husband she must kill to truly be free. A Vigilante is a thriller inspired by the strength and bravery of real domestic abuse survivors and the incredible obstacles to safety they face.",Sarah Daggar-Nickson,female,92,50,"Led by Olivia Wilde's fearless performance and elevated by timely themes, A Vigilante is an uncompromising thriller that hits as hard as its protagonist.",-0.0334
4,After,PG-13,"Drama, Romance",4/12/19,"Based on Anna Todd's best-selling novel which became a publishing sensation on social storytelling platform Wattpad, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart, as she enters her first semester in college. Armed with grand ambitions for her future, her guarded world opens up when she meets the dark and mysterious Hardin Scott (Tiffin), a magnetic, brooding rebel who makes her question all she thought she knew about herself and what she wants out of life.",Jenny Gage,female,17,72,"Tepid and tired, After's fun flourishes are let down by its generic story.",0.9349
...,...,...,...,...,...,...,...,...,...,...,...
161,Velvet Buzzsaw,R,"Comedy, Drama, Mystery & Suspense",2/1/19,"Velvet Buzzsaw is a satirical thriller set in the contemporary art world scene of Los Angeles, where big money artists and mega-collectors pay a high price when art collides with commerce.",Dan Gilroy,male,63,36,If you only watch one art-world satire with horror overtones this year -- or most others -- it should probably be Velvet Buzzsaw.,-0.2732
162,What Men Want,R,Comedy,2/8/19,"Inspired by the Nancy Meyers hit romantic comedy WHAT WOMEN WANT, this film follows the story of a female sports agent (Henson) who has been constantly boxed out by her male colleagues. When she gains the power to hear mens' thought, she is able to shift the paradigm to her advantage as she races to sign the NBA's next superstar",Adam Shankman,male,44,33,"Admittedly uneven but easy to like, What Men Want proves a gender-swapped remake can work -- and the odds are substantially improved with Taraji P. Henson in the lead.",0.9158
163,Wild Rose,R,"Comedy, Drama",6/21/19,"WILD ROSE tells the complicated story of Rose-Lynn, a woman on a quest to become a country music star, while also grappling with the responsibilities of being recently released from prison and a young mother of two children.",Tom Harper,male,93,88,"There's no shortage of star-is-born stories, but Wild Rose proves they can still be thoroughly entertaining -- and marks its own transcendent moment for lead Jessie Buckley.",-0.5106
164,Wine Country,R,Comedy,5/8/19,"In honor of Rebecca (Rachel Dratch)'s 50th birthday, Abby (Amy Poehler) plans a scenic Napa getaway with their best, longtime friends. Workaholic Catherine (Ana Gasteyer), post-op Val (Paula Pell), homebody Jenny (Emily Spivey), and weary mom Naomi (Maya Rudolph) are equally sold on the chance to relax and reconnect. Yet as the alcohol flows, real world uncertainties intrude on the punchlines and gossip, and the women begin questioning their friendships and futures.",Amy Poehler,female,66,30,"Wine Country's comedy might not be quite as robust as fans of this ensemble will expect, but it's got sweetness on the nose and a nicely balanced finish.",0.9081
165,Yesterday,PG-13,"Comedy, Science Fiction & Fantasy, Romance",6/28/19,"Jack Malik (Himesh Patel, BBC's Eastenders) is a struggling singer-songwriter in a tiny English seaside town whose dreams of fame are rapidly fading, despite the fierce devotion and support of his childhood best friend, Ellie (Lily James, Mamma Mia! Here We Go Again). Then, after a freak bus accident during a mysterious global blackout, Jack wakes up to discover that The Beatles have never existed... and he finds himself with a very complicated problem, indeed.",Danny Boyle,male,63,89,"Yesterday may fall short of fab, but the end result is still a sweetly charming fantasy with an intriguing -- albeit somewhat under-explored -- premise.",0.1365

In [7]:
phrase = df.movie_info[1]
phrase

'Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.'

In [8]:
analyzer = SentimentIntensityAnalyzer()
analyzer.polarity_scores(phrase)['compound']

0.9237

In [9]:
# Sort
TopNegv = df.sort_values(by = ['sentiment_score']).head(10)
TopNegv

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus,sentiment_score
7,All Is True,PG-13,"Art House & International, Drama",5/10/19,"The year is 1613, Shakespeare is acknowledged as the greatest writer of the age. But disaster strikes when his renowned Globe Theatre burns to the ground, and devastated, Shakespeare returns to Stratford, where he must face a troubled past and a neglected family. Haunted by the death of his only son Hamnet, he struggles to mend the broken relationships with his wife and daughters. In so doing, he is ruthlessly forced to examine his own failings as husband and father. His very personal search for the truth uncovers secrets and lies within a family at war.",Kenneth Branagh,male,71,73,"Impressively cast and beautifully filmed, All Is True takes an elegiac look at Shakespeare's final days.",-0.9955
148,The Wind,R,Horror,4/5/19,"An unseen evil haunts the homestead in this chilling, folkloric tale of madness, paranoia, and otherworldly terror. Lizzy (Caitlin Gerard) is a tough, resourceful frontierswoman settling a remote stretch of land on the 19th-century American frontier. Isolated from civilization in a desolate wilderness where the wind never stops howling, she begins to sense a sinister presence that seems to be borne of the land itself, an overwhelming dread that her husband (Ashley Zukerman) dismisses as superstition. When a newlywed couple arrives on a nearby homestead, their presence amplifies Lizzy's fears, setting into motion a shocking chain of events. Masterfully blending haunting visuals with pulse-pounding sound design, director Emma Tammi evokes a godforsaken world in which the forces of nature come alive with quivering menace.",Emma Tammi,female,81,55,"Imperfect yet intriguing, The Wind offers horror fans an admirably ambitious story further distinguished by its fresh perspective and effective scares.",-0.9838
83,Nightmare Cinema,R,Horror,6/21/19,"In this twisted horror anthology, five strangers are drawn to an abandoned theater and forced to watch their deepest and darkest fears play out before them. Lurking in the shadows is the Projectionist, who preys upon their souls with his collection of disturbing films. As each reel spins its sinister tale, the characters find frightening parallels to their own lives.","Alejandro Brugués, Joe Dante, Ryuhei Kitamura, David Slade, Mick Garris",male,77,51,"Admirably eclectic yet more consistent than most horror anthologies, Nightmare Cinema should entertain viewers in the mood for a good old-fashioned creepshow.",-0.9756
154,Triple Threat,R,"Action & Adventure, Art House & International",3/22/19,"TRIPLE THREAT, the newest feature from Johnson, is an adrenaline fueled and gritty action thriller starring some of the biggest names in action today. Michael Jai White (BLACK DYNAMITE; UNDISPUTED 2: LAST MAN STANDING), Scott Adkins (Marvel's DOCTOR STRANGE; THE EXPENDABLES 2), Michael Bisping (xXx: RETURN OF XANDER CAGE) star as a group of professional assassins hired to take out a billionaire's daughter who is intent on bringing down a major crime syndicate. A down and out team of mercenaries, played by Tony Jaa (ONG BAK TRILOGY; xXx: RETURN OF XANDER CAGE), Iko Uwais (THE RAID 1 & 2; STAR WARS: THE FORCE AWAKENS) and Tiger Chen (MAN OF TAI CHI), must take on the assassins and stop them before they kill their target. The film co-stars JeeJa Yanin (CHOCOLATE) Michael Wong (Cold War) and Celina Jade (WOLF WARRIOR 2).",Jesse V. Johnson,male,70,36,"Triple Threat might have made better use of its attention-getting cast, but action fans should still find the end results entertaining enough to rate a rental.",-0.9696
11,Angel of Mine,R,"Drama, Mystery & Suspense",8/30/19,"Noomi Rapace (The Girl with the Dragon Tattoo) stars as a woman on the edge in this intense psychological thriller. Having suffered a tragic loss years earlier, Lizzie (Rapace) is trying to rebuild her life when she suddenly becomes obsessed with a neighbor's daughter, believing the girl to be her own child. As Lizzie's shocking, threatening acts grow increasingly dangerous, they lead to an explosive confrontation with the girl's angry, defensive mother (Yvonne Strahovski, ""The Handmaid's Tale"").",Kim Farrant,female,68,95,NaN,-0.9687
27,Charlie Says,R,Drama,5/10/19,"Three young women were sentenced to death for the infamous Manson murders. Their sentences became life imprisonment when the death penalty was lifted in California. One young graduate student was sent in to teach them. Through her, we witness their transformations as they face the reality of their horrific crimes.",Mary Harron,female,60,80,"Charlie Says approaches its infamous subject from a welcome new angle, but suffers from a disappointing lack of depth in its treatment of the story.",-0.9643
113,The Curse of La Llorona,R,Horror,4/19/19,"In 1970s Los Angeles, La Llorona is stalking the night -- and the children. Ignoring the eerie warning of a troubled mother suspected of child endangerment, a social worker and her own small kids are soon drawn into a frightening supernatural realm. Their only hope to survive La Llorona's deadly wrath may be a disillusioned priest and the mysticism he practices to keep evil at bay, on the fringes where fear and faith collide.",Michael Chaves,male,29,41,"Content to coast on jump scares rather than tap into its story's creepy potential, The Curse of La Llorona arrives in theaters already broken.",-0.9628
87,Pet Sematary,R,Horror,4/5/19,"Based on the seminal horror novel by Stephen King, Pet Sematary follows Dr. Louis Creed (Jason Clarke), who, after relocating with his wife Rachel (Amy Seimetz) and their two young children from Boston to rural Maine, discovers a mysterious burial ground hidden deep in the woods near the family's new home. When tragedy strikes, Louis turns to his unusual neighbor, Jud Crandall (John Lithgow), setting off a perilous chain reaction that unleashes an unfathomable evil with horrific consequences.","Kevin Kölsch, Dennis Widmyer",male,57,34,"Pet Sematary takes its source material in a few different directions, but this remake feels like an exhuming almost as often as it does a revival.",-0.9590
142,The Standoff at Sparrow Creek,NR,"Drama, Mystery & Suspense",1/18/19,"After a mass shooting at a police funeral, reclusive ex-cop Gannon finds himself unwittingly forced out of retirement when he realizes that the killer belongs to the same militia he joined after quitting the force. Understanding that the shooting could set off a chain reaction of copycat violence across the country, Gannon quarantines his fellow militiamen in the remote lumber mill they call their headquarters. There, he sets about a series of grueling interrogations, intent on ferreting out the killer and turning him over to the authorities to prevent further bloodshed.",Henry Dunham,male,77,67,"Taut and unpredictable, The Standoff at Sparrow Creek should satisfy suspense fans in the mood for a well-told story topped with a generous helping of violence.",-0.9590
40,El Chicano,R,"Action & Adventure, Drama",5/3/19,"When L.A.P.D. Detective Diego Hernandez is assigned a career-making case investigating a vicious cartel, he uncovers links to his brother's supposed suicide and a turf battle that's about to swallow his neighborhood. Torn between playing by the book and seeking justice, he resurrects the masked street legend El Chicano. Now, out to take down his childhood buddy turned gang boss, he sets off a bloody war to defend his city and avenge his brother's murder",Ben Hernandez Bray,male,38,60,"El Chicano represents a step forward for representation in superhero cinema -- unfortunately, its clichéd story is nothing more than ordinary.",-0.9578

In [10]:
TopPosv = df.sort_values(by = ['sentiment_score']).tail(10)
TopPosv[['movie_title', 'sentiment_score']]

           movie_title  sentiment_score
71           Long Shot           0.9778
36               Dumbo           0.9801
0      A Dog's Journey           0.9837
49   Giant Little Ones           0.9839
93            Red Joan           0.9848
156          UglyDolls           0.9862
48     Five Feet Apart           0.9889
130     The Laundromat           0.9908
81        Missing Link           0.9909
23        Breakthrough           0.9915

## 2. Text Classification

1. Clean and normalize the _movie_info_ column using the _maven_text_preprocessing.py_ module
2. Create a Count Vectorizer
* Remove stop words
* Set the minimum document frequency to 10%
3. Create a Naïve Bayes model and a Logistic Regression model to predict which movies are directed by women vs men using the CV
4. Compare their accuracy scores and classification reports
5. Using the better performing model, return the top 5 movies that the model predicts are most likely directed by a women

In [11]:
# import libraries
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

In [12]:
import maven_text_preprocessing

In [13]:
df.head(2)

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus,sentiment_score
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit.",0.9837
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity.",0.9237

In [14]:
#Clean & Normalization
clean_MI = maven_text_preprocessing.clean_and_normalize(df.movie_info)
clean_MI

0      bailey voice josh gad live good life michigan farm boy ethan dennis quaid ethans wife hannah marg helgenberger new playmate ethan hannah baby granddaughter cj problem cjs mom gloria betty gilpin decide cj away bailey soul prepare leave life new make promise ethan find cj protect cost begin bailey adventure multiple life fill love friendship devotion cj kathryn prescott cjs good friend trent henry lau experience joy heartbreak music laughter good belly rub
1                                                                                                                                                                                                                                                                                                                                       separate owner dog set 400mile journey safety security place call home way meet series new friend manage bring little bit comfort joy life
2                                                                                                                                                                                            leader new orleans famed preservation hall jazz band seek fulfill late father dream retrace musical root shore cuba search indigenous music give birth new orleans jazz tuba cuba celebrate triumph human spirit express universal language music challenge resolve build bridge wall
3                                                                                                                                                                                                                                                                           abuse woman sadie olivia wilde devote rid victim domestic abuser hunt husband kill truly free vigilante thriller inspire strength bravery real domestic abuse survivor incredible obstacle safety face
4                                                                                                                     base anna todd bestselle novel publishing sensation social storytelling platform wattpad follow tessa langford dedicated student dutiful daughter loyal girlfriend high school sweetheart enter semester college arm grand ambition future guard world open meet dark mysterious hardin scott tiffin magnetic brood rebel make question think know want life
                                                                                                                                                                                                                                          ...
161                                                                                                                                                                                                                                                                                                                              velvet buzzsaw satirical thriller set contemporary art world scene los angeles big money artist megacollector pay high price art collide commerce
162                                                                                                                                                                                                                                                                  inspire nancy meyer hit romantic comedy woman want film follow story female sport agent henson constantly box male colleague gain power hear men think able shift paradigm advantage race sign nbas superstar
163                                                                                                                                                                                                                                                                                                                                     wild rose tell complicated story roselynn woman quest country music star grapple responsibility recently release prison young mother child
164                                                                                                             honor rebecca rachel dratchs 50th birthday abby amy poehler plan scenic napa getaway good longtime friend workaholic catherine ana gasteyer postop val paula pell homebody jenny emily spivey weary mom naomi maya rudolph equally sell chance relax reconnect alcohol flow real world uncertainty intrude punchline gossip woman begin question friendship future
165                                                                                                                                                                     jack malik himesh patel bbcs eastender struggle singersongwriter tiny english seaside town dream fame rapidly fade despite fierce devotion support childhood good friend ellie lily james mamma mia freak bus accident mysterious global blackout jack wake discover beatle exist find complicated problem
Name: movie_info, Length: 166, dtype: str

In [15]:
#Count Vectorizer
cv = CountVectorizer(stop_words = 'english', min_df = .1)
X = cv.fit_transform(clean_MI)
X_df = pd.DataFrame(X.toarray(), columns=cv.get_feature_names_out())
X_df

,begin,discover,family,film,follow,force,friend,home,leave,life,...,man,new,set,star,story,turn,woman,world,year,young
0,1,0,0,0,0,0,1,0,1,3,...,0,2,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,1,1,0,1,...,0,1,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
162,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
163,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,1,0,0,1
164,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,1,0,0
165,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
# TF-IDF

tv = TfidfVectorizer(stop_words = 'english', min_df = .1)
Xt = tv.fit_transform(clean_MI)
Xt_df = pd.DataFrame(Xt.toarray(), columns=tv.get_feature_names_out())
Xt_df

,begin,discover,family,film,follow,force,friend,home,leave,life,...,man,new,set,star,story,turn,woman,world,year,young
0,0.282820,0.000000,0.0,0.000000,0.000000,0.0,0.244936,0.000000,0.296518,0.635681,...,0.0,0.458654,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
1,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.437857,0.491047,0.000000,0.378789,...,0.0,0.409954,0.505580,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
2,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,1.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000
3,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.00000,0.000000,0.0,1.000000,0.000000,0.0,0.000000
4,0.000000,0.000000,0.0,0.000000,0.675662,0.0,0.000000,0.000000,0.000000,0.513763,...,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.528705,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.791943,0.00000,0.000000,0.0,0.000000,0.610595,0.0,0.000000
162,0.000000,0.000000,0.0,0.521979,0.529535,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.00000,0.449990,0.0,0.494610,0.000000,0.0,0.000000
163,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.55909,0.446502,0.0,0.490777,0.000000,0.0,0.497184
164,0.559761,0.000000,0.0,0.000000,0.000000,0.0,0.484780,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.515164,0.431580,0.0,0.000000
165,0.000000,0.760834,0.0,0.000000,0.000000,0.0,0.648946,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.00000,0.000000,0.0,0.000000,0.000000,0.0,0.000000

In [17]:
# Define Y [Label]
y = df.director_gender
y.head(2)

0    female
1      male
Name: director_gender, dtype: str

In [18]:
# CV, Naive Bayes
X_train, X_test, y_train, y_test = train_test_split(X_df,y,test_size=0.2,random_state=42)

# Train Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)
print('Accuracy',accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy 0.7941176470588235
              precision    recall  f1-score   support

      female       0.25      0.20      0.22         5
        male       0.87      0.90      0.88        29

    accuracy                           0.79        34
   macro avg       0.56      0.55      0.55        34
weighted avg       0.78      0.79      0.78        34

In [19]:
# LCV , ogistic Regression

# Train LR
model_lr = LogisticRegression()
model_lr.fit(X_train, y_train)

# Prediction
y_pred = model_lr.predict(X_test)
print('Accuracy',accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy 0.7647058823529411
              precision    recall  f1-score   support

      female       0.29      0.40      0.33         5
        male       0.89      0.83      0.86        29

    accuracy                           0.76        34
   macro avg       0.59      0.61      0.60        34
weighted avg       0.80      0.76      0.78        34

In [20]:
model_lr.classes_

array(['female', 'male'], dtype=object)

In [21]:
model_lr.predict_proba(X_df)[:,0]

array([0.54526428, 0.10707387, 0.09824327, 0.35235055, 0.37588659,
       0.13652366, 0.51559699, 0.0294785 , 0.02946028, 0.11601882,
       0.12396461, 0.39465836, 0.15234872, 0.07198651, 0.12882296,
       0.11084223, 0.61054727, 0.07108008, 0.16950357, 0.40625388,
       0.24893195, 0.34746799, 0.18809777, 0.41440522, 0.15234872,
       0.35020858, 0.25230079, 0.72175165, 0.25525125, 0.03509234,
       0.03225464, 0.11849757, 0.03969183, 0.15347058, 0.25525125,
       0.05087731, 0.04071751, 0.10466363, 0.59734963, 0.13652366,
       0.05651761, 0.32371779, 0.13652366, 0.12056163, 0.36357149,
       0.13652366, 0.48685639, 0.00881581, 0.17991343, 0.19161523,
       0.15381419, 0.21273848, 0.09930269, 0.38086115, 0.14566466,
       0.84025231, 0.01458519, 0.01066855, 0.04509013, 0.15381419,
       0.18219456, 0.31277811, 0.24380442, 0.13437157, 0.30148787,
       0.11899226, 0.03969183, 0.12293186, 0.15234872, 0.6209547 ,
       0.57199226, 0.38212186, 0.20108317, 0.04437635, 0.03945265,
       0.22639202, 0.67133827, 0.08309039, 0.07543305, 0.06982441,
       0.15234872, 0.01749035, 0.30192789, 0.18885579, 0.39506943,
       0.51835883, 0.21589175, 0.03837364, 0.25310002, 0.01830832,
       0.12950297, 0.1510783 , 0.54114351, 0.4556308 , 0.06362075,
       0.27785109, 0.13652366, 0.56415376, 0.49430924, 0.20764213,
       0.0472736 , 0.05701589, 0.42709869, 0.11385951, 0.06340882,
       0.14680417, 0.15381419, 0.10839885, 0.19914346, 0.14900771,
       0.21935809, 0.0751542 , 0.16406606, 0.13652366, 0.10452504,
       0.02351259, 0.35235055, 0.19020926, 0.28116808, 0.14238242,
       0.28454696, 0.18491427, 0.30192789, 0.11019736, 0.16714882,
       0.15244888, 0.15815429, 0.14465055, 0.16808764, 0.11385951,
       0.10817092, 0.10901988, 0.04686213, 0.21903102, 0.05238699,
       0.13652366, 0.04634303, 0.05922039, 0.20520106, 0.12226963,
       0.69204788, 0.19175928, 0.07704347, 0.34929277, 0.05133606,
       0.14643052, 0.12454864, 0.19640983, 0.34717772, 0.07658786,
       0.36533494, 0.14564698, 0.18246289, 0.04435785, 0.03032369,
       0.00787573, 0.18296315, 0.36971258, 0.29597796, 0.35235055,
       0.00565224, 0.19732527, 0.56132462, 0.44780253, 0.55499617,
       0.13822784])

In [22]:
df['Score_NB'] = model.predict_proba(X_df)[:,0]

In [23]:
df.sort_values(by = 'Score_NB', ascending=False).head(5)

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus,sentiment_score,Score_NB
27,Charlie Says,R,Drama,5/10/19,"Three young women were sentenced to death for the infamous Manson murders. Their sentences became life imprisonment when the death penalty was lifted in California. One young graduate student was sent in to teach them. Through her, we witness their transformations as they face the reality of their horrific crimes.",Mary Harron,female,60,80,"Charlie Says approaches its infamous subject from a welcome new angle, but suffers from a disappointing lack of depth in its treatment of the story.",-0.9643,0.801111
55,Greta,R,Drama,3/1/19,"A sweet, naïve young woman trying to make it on her own in New York City, Frances (Chloë Grace Moretz) doesn't think twice about returning the handbag she finds on the subway to its rightful owner. That owner is Greta (Isabelle Huppert), an eccentric French piano teacher with a love for classical music and an aching loneliness. Having recently lost her mother, Frances quickly grows closer to widowed Greta. The two become fast friends - but Greta's maternal charms begin to dissolve and grow increasingly disturbing as Frances discovers that nothing in Greta's life is what it seems in this suspense thriller from Academy Award (R) winning director Neil Jordan.",Neil Jordan,male,60,41,"A bonkers B movie occasionally elevated by its A-list talent, Greta dives headlong into camp and struggles to stay afloat.",0.9042,0.758448
69,Little,PG-13,Comedy,4/12/19,"Marsai Martin (TV's Black-ish) stars in and executive produces Universal Pictures' LITTLE, a comedy from producer Will Packer (Girls Trip, Ride Along and Think Like a Man series) based on an idea the young actress pitched. Directed by Tina Gordon (Peeples), the film tells the story of a woman who-when the pressures of adulthood become too much to bear-gets the chance to relive the carefree life of her younger self.",Tina Gordon Chism,female,47,63,"A disappointingly uneven but overall agreeable spin on a familiar formula, Little benefits from a big heart -- and a story that makes good use of its talented, well-matched cast.",0.7794,0.715214
38,Egg,NR,Comedy,1/18/19,"An unflinching comedy about why women choose motherhood, why they revere it, fear it, and why some women choose to forgo it. Over the course of one explosive evening, two couples and a surrogate must face their own ridiculous and sometimes heartbreaking shortcomings. With sharp cutting dialogue and complicated characters, EGG is about the personal, social, professional, and ideological implications of bringing new life into the world. Artist Tina (Alysia Reiner, ""Orange Is the New Black"") and her passive-aggressive feminist husband (Gbenga Akinnagbe, ""The Deuce"") invite her eight-months pregnant art school rival (Christina Hendricks,""Mad Men"") and power hungry, new-money husband (David Alan Basche, The Exes) to their Brooklyn loft, surprising them with Tina's new work-in-progress: a radical alternative to motherhood. But when their sensuous, non-traditional surrogate arrives (Anna Camp, Pitch Perfect) the truth comes out, and the patriarchy fights to hang on by its teeth.",Marianna Palka,female,100,43,NaN,0.4497,0.680241
140,The Secret Life of Pets 2,PG,"Animation, Comedy",6/7/19,"THE SECRET LIFE OF PETS 2 will follow summer 2016's blockbuster about the lives our pets lead after we leave for work or school each day. Illumination founder and CEO Chris Meledandri and his longtime collaborator Janet Healy will produce the sequel to the comedy that had the best opening ever for an original film, animated or otherwise. THE SECRET LIFE OF PETS 2 will see the return of writer Brian Lynch (Minions) and once again be directed by Chris Renaud (Despicable Me series, Dr. Seuss' The Lorax).","Chris Renaud, Jonathan Del Val",male,59,90,"The Secret Life of Pets 2 doesn't teach its animated stars any new narrative tricks -- but for fans of the original, this funny, energetic sequel should still satisfy.",0.9136,0.629178

## 3. Topic Modeling

1. Using the same preprocessed data as the last assignment, create a Tfidf Vectorizer
* Remove stop words
* Start with min_df = 0.05 and max_df=0.2
2. Create an NMF model to find the main topics in the movie descriptions
* Start with n_components=2
3. Tweak the model by updating the Tfidf Vectorizer parameters and number of topics
4. Interpret and name the topics
5. For two of the topics, return the top movies that contain the topic

In [96]:
# TF-IDF
tv2 = TfidfVectorizer(stop_words = 'english', min_df = .02, max_df = .2)
Xt_df2 = tv2.fit_transform(clean_MI)
Xt_df2 = pd.DataFrame(Xt_df2.toarray(), columns=tv2.get_feature_names_out())
Xt_df2

,abandon,ability,academy,act,action,adventure,allnew,ambition,american,amy,...,win,winner,woman,wood,work,write,writer,year,york,young
0,0.0,0.0,0.0,0.0,0.0,0.173939,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.242848,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.250586,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
162,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.214218,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
163,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.236069,0.0,0.0,0.0,0.0,0.0,0.0,0.239151
164,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.379297,...,0.0,0.0,0.234364,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
165,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.000000

In [97]:
# NMf
from sklearn.decomposition import NMF
nmf = NMF(n_components = 5, random_state = 42)
W = nmf.fit_transform(Xt_df2)
H = nmf.components_

In [98]:
def display_topic(H):
    for topic_num,topic_array in enumerate(H):
        top_features = topic_array.argsort()[::-1][:10]
        top_words = [tv2.get_feature_names_out()[i] for i in top_features]
        print(f'Topic {topic_num}: '+', '.join(top_words))

In [99]:
display_topic(H)

Topic 0: family, grow, father, young, face, return, son, death, home, try
Topic 1: film, true, star, base, follow, inspire, comedy, tell, man, event
Topic 2: friend, good, live, dream, love, leave, meet, school, help, childhood
Topic 3: set, force, child, evil, sinister, night, horror, neighborhood, follow, deadly
Topic 4: academy, award, winner, nominee, help, violent, turn, skill, include, jason

In [105]:
topic = pd.DataFrame(W)
topic.columns=['Family', 'Family Movie', 'Friendship', 'Horor','Big Budget']
topic

       Family  Family Movie  Friendship     Horor  Big Budget
0    0.000000      0.000000    0.380883  0.000000    0.000000
1    0.000000      0.000000    0.139142  0.215053    0.000000
2    0.008571      0.045552    0.115010  0.000000    0.003595
3    0.084739      0.119402    0.000000  0.000000    0.003242
4    0.000000      0.103910    0.129381  0.068859    0.000000
..        ...           ...         ...       ...         ...
161  0.000000      0.000000    0.000000  0.202888    0.003122
162  0.000000      0.340238    0.000000  0.000000    0.000000
163  0.030216      0.158415    0.000000  0.069271    0.014434
164  0.000000      0.000000    0.296027  0.000000    0.000000
165  0.000000      0.000000    0.311814  0.000000    0.000000

[166 rows x 5 columns]

In [101]:
df

,movie_title,rating,genre,in_theaters_date,movie_info,directors,director_gender,tomatometer_rating,audience_rating,critics_consensus,sentiment_score,Score_NB
0,A Dog's Journey,PG,"Drama, Kids & Family",5/17/19,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",Gail Mancuso,female,50,92,"A Dog's Journey is as sentimental as one might expect, but even cynical viewers may find their ability to resist shedding a tear stretched to the puppermost limit.",0.9837,0.539789
1,A Dog's Way Home,PG,Drama,1/11/19,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",Charles Martin Smith,male,60,71,"A Dog's Way Home may not quite be a family-friendly animal drama fan's best friend, but this canine adventure is no less heartwarming for its familiarity.",0.9237,0.071577
2,A Tuba to Cuba,NR,"Documentary, Musical & Performing Arts",2/15/19,"The leader of New Orleans' famed Preservation Hall Jazz Band seeks to fulfill his late father's dream of retracing their musical roots to the shores of Cuba in search of the indigenous music that gave birth to New Orleans jazz. A TUBA TO CUBA celebrates the triumph of the human spirit expressed through the universal language of music and challenges us to resolve to build bridges, not walls.","Danny Clinch, T.G. Herrington",male,100,82,NaN,0.9360,0.178764
3,A Vigilante,R,Drama,3/29/19,"A once abused woman, Sadie (Olivia Wilde), devotes herself to ridding victims of their domestic abusers while hunting down the husband she must kill to truly be free. A Vigilante is a thriller inspired by the strength and bravery of real domestic abuse survivors and the incredible obstacles to safety they face.",Sarah Daggar-Nickson,female,92,50,"Led by Olivia Wilde's fearless performance and elevated by timely themes, A Vigilante is an uncompromising thriller that hits as hard as its protagonist.",-0.0334,0.427592
4,After,PG-13,"Drama, Romance",4/12/19,"Based on Anna Todd's best-selling novel which became a publishing sensation on social storytelling platform Wattpad, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart, as she enters her first semester in college. Armed with grand ambitions for her future, her guarded world opens up when she meets the dark and mysterious Hardin Scott (Tiffin), a magnetic, brooding rebel who makes her question all she thought she knew about herself and what she wants out of life.",Jenny Gage,female,17,72,"Tepid and tired, After's fun flourishes are let down by its generic story.",0.9349,0.361593
...,...,...,...,...,...,...,...,...,...,...,...,...
161,Velvet Buzzsaw,R,"Comedy, Drama, Mystery & Suspense",2/1/19,"Velvet Buzzsaw is a satirical thriller set in the contemporary art world scene of Los Angeles, where big money artists and mega-collectors pay a high price when art collides with commerce.",Dan Gilroy,male,63,36,If you only watch one art-world satire with horror overtones this year -- or most others -- it should probably be Velvet Buzzsaw.,-0.2732,0.159589
162,What Men Want,R,Comedy,2/8/19,"Inspired by the Nancy Meyers hit romantic comedy WHAT WOMEN WANT, this film follows the story of a female sports agent (Henson) who has been constantly boxed out by her male colleagues. When she gains the power to hear mens' thought, she is able to shift the paradigm to her advantage as she races to sign the NBA's next superstar",Adam Shankman,male,44,33,"Admittedly uneven but easy to like, What Men Want proves a gender-swapped remake can work -- and the odds are substantially improved with Taraji P. Henson in the lead.",0.9158,0.507091
163,Wild Rose,R,"Comedy, Drama",6/21/19,"WILD ROSE tells the complicated story of Rose-Lynn, a woman on a quest to become a country music star, while also grappling with the responsibilities of being recently released from prison and a young mother of two children.",Tom Harper,male,93,88,"There's no shortage of star-is-born stories, but Wild Rose proves they can still be thoroughly entertaining -- and marks its own transcendent moment for lead Jessie Buckley.",-0.5106,0.552478
164,Wine Country,R,Comedy,5/8/19,"In honor of Rebecca (Rachel Dratch)'s 50th birthday, Abby (Amy Poehler) plans a scenic Napa getaway with their best, longtime friends. Workaholic Catherine (Ana Gasteyer), post-op Val (Paula Pell), homebody Jenny (Emily Spivey), and weary mom Naomi (Maya Rudolph) are equally sold on the chance to relax and reconnect. Yet as the alcohol flows, real world uncertainties intrude on the punchlines and gossip, and the women begin questioning their friendships and futures.",Amy Poehler,female,66,30,"Wine Country's comedy might not be quite as robust as fans of this ensemble will expect, but it's got sweetness on the nose and a nicely balanced finish.",0.9081,0.438776
165,Yesterday,PG-13,"Comedy, Science Fiction & Fantasy, Romance",6/28/19,"Jack Malik (Himesh Patel, BBC's Eastenders) is a struggling singer-songwriter in a tiny English seaside town whose dreams of fame are rapidly fading, despite the fierce devotion and support of his childhood best friend, Ellie (Lily James, Mamma Mia! Here We Go Again). Then, after a freak bus accident during a mysterious global blackout, Jack wakes up to discover that The Beatles have never existed... and he finds himself with a very complicated problem, indeed.",Danny Boyle,male,63,89,"Yesterday may fall short of fab, but the end result is still a sweetly charming fantasy with an intriguing -- albeit somewhat under-explored -- premise.",0.1365,0.161418

In [108]:
Movie_topic = pd.concat([df[['movie_info','movie_title']],topic],axis = 1)
Movie_topic.head(2)

,movie_info,movie_title,Family,Family Movie,Friendship,Horor,Big Budget
0,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",A Dog's Journey,0.0,0.0,0.380883,0.000000,0.0
1,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",A Dog's Way Home,0.0,0.0,0.139142,0.215053,0.0

In [109]:
Movie_topic['Top_Topic'] = Movie_topic.iloc[:, 2:].idxmax(axis = 1)

In [110]:
Movie_topic

,movie_info,movie_title,Family,Family Movie,Friendship,Horor,Big Budget,Top_Topic
0,"Bailey (voiced again by Josh Gad) is living the good life on the Michigan farm of his ""boy,"" Ethan (Dennis Quaid) and Ethan's wife Hannah (Marg Helgenberger). He even has a new playmate: Ethan and Hannah's baby granddaughter, CJ. The problem is that CJ's mom, Gloria (Betty Gilpin), decides to take CJ away. As Bailey's soul prepares to leave this life for a new one, he makes a promise to Ethan to find CJ and protect her at any cost. Thus begins Bailey's adventure through multiple lives filled with love, friendship and devotion as he, CJ (Kathryn Prescott), and CJ's best friend Trent (Henry Lau) experience joy and heartbreak, music and laughter, and few really good belly rubs.",A Dog's Journey,0.000000,0.000000,0.380883,0.000000,0.000000,Friendship
1,"Separated from her owner, a dog sets off on an 400-mile journey to get back to the safety and security of the place she calls home. Along the way, she meets a series of new friends and manages to bring a little bit of comfort and joy to their lives.",A Dog's Way Home,0.000000,0.000000,0.139142,0.215053,0.000000,Horor
2,"The leader of New Orleans' famed Preservation Hall Jazz Band seeks to fulfill his late father's dream of retracing their musical roots to the shores of Cuba in search of the indigenous music that gave birth to New Orleans jazz. A TUBA TO CUBA celebrates the triumph of the human spirit expressed through the universal language of music and challenges us to resolve to build bridges, not walls.",A Tuba to Cuba,0.008571,0.045552,0.115010,0.000000,0.003595,Friendship
3,"A once abused woman, Sadie (Olivia Wilde), devotes herself to ridding victims of their domestic abusers while hunting down the husband she must kill to truly be free. A Vigilante is a thriller inspired by the strength and bravery of real domestic abuse survivors and the incredible obstacles to safety they face.",A Vigilante,0.084739,0.119402,0.000000,0.000000,0.003242,Family Movie
4,"Based on Anna Todd's best-selling novel which became a publishing sensation on social storytelling platform Wattpad, AFTER follows Tessa (Langford), a dedicated student, dutiful daughter and loyal girlfriend to her high school sweetheart, as she enters her first semester in college. Armed with grand ambitions for her future, her guarded world opens up when she meets the dark and mysterious Hardin Scott (Tiffin), a magnetic, brooding rebel who makes her question all she thought she knew about herself and what she wants out of life.",After,0.000000,0.103910,0.129381,0.068859,0.000000,Friendship
...,...,...,...,...,...,...,...,...
161,"Velvet Buzzsaw is a satirical thriller set in the contemporary art world scene of Los Angeles, where big money artists and mega-collectors pay a high price when art collides with commerce.",Velvet Buzzsaw,0.000000,0.000000,0.000000,0.202888,0.003122,Horor
162,"Inspired by the Nancy Meyers hit romantic comedy WHAT WOMEN WANT, this film follows the story of a female sports agent (Henson) who has been constantly boxed out by her male colleagues. When she gains the power to hear mens' thought, she is able to shift the paradigm to her advantage as she races to sign the NBA's next superstar",What Men Want,0.000000,0.340238,0.000000,0.000000,0.000000,Family Movie
163,"WILD ROSE tells the complicated story of Rose-Lynn, a woman on a quest to become a country music star, while also grappling with the responsibilities of being recently released from prison and a young mother of two children.",Wild Rose,0.030216,0.158415,0.000000,0.069271,0.014434,Family Movie
164,"In honor of Rebecca (Rachel Dratch)'s 50th birthday, Abby (Amy Poehler) plans a scenic Napa getaway with their best, longtime friends. Workaholic Catherine (Ana Gasteyer), post-op Val (Paula Pell), homebody Jenny (Emily Spivey), and weary mom Naomi (Maya Rudolph) are equally sold on the chance to relax and reconnect. Yet as the alcohol flows, real world uncertainties intrude on the punchlines and gossip, and the women begin questioning their friendships and futures.",Wine Country,0.000000,0.000000,0.296027,0.000000,0.000000,Friendship
165,"Jack Malik (Himesh Patel, BBC's Eastenders) is a struggling singer-songwriter in a tiny English seaside town whose dreams of fame are rapidly fading, despite the fierce devotion and support of his childhood best friend, Ellie (Lily James, Mamma Mia! Here We Go Again). Then, after a freak bus accident during a mysterious global blackout, Jack wakes up to discover that The Beatles have never existed... and he finds himself with a very complicated problem, indeed.",Yesterday,0.000000,0.000000,0.311814,0.000000,0.000000,Friendship